// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    // url: process.env['DATABASE_URL'], //這裡使用 DATABASE_URL，因為它是連接到本地端資料庫的 URL，適合用於應用程式的運行時連接。
    url: process.env['DIRECT_URL'], // 這裡使用 DIRECT_URL，因為它是直接連接到資料庫的 URL，適合用於 Prisma CLI 的操作，如遷移和生成 Prisma Client。
  },
});
